[package]
name = "ggnerf_datasetgenerator_rs"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-sc2 = "1.1.2"
num-traits = "0.2.14"